### ISSUE TITLE
Build a tree from clustering

### ISSUE THREAD

**Issue by leoisl** [mbhall88/tbpore#36]
This is a request from Floriane and Pedro from our meeting on 18/05/2022.

After clustering the samples, we should build a tree from it. I have no idea which would be the best tool do build such a tree... @iqbal-lab  @mbhall88 @jeff-k @martinghunt any ideas?

**Comment by leoisl** [comment]
Hello again.

This is a message from Floriane by e-mail:
> Just to let you know that I gave a trial with tbpore cluster and it was working well. I was able to observe some samples in the same cluster as expected. But again, I am wondering if possible to get more than just a list a cluster (like a tree for example). The goal would be also to see if samples, even if not in the same cluster, are genetically more or less close to each other.

I think this might be an important issue. Basically this means that our clustering is not very useful to them. They want to be able to see all samples and how distant they are in a tree structure. I also don't know anything about trees, but we do calculate the all-pair distances between all samples, so this could potentially be somehow an input to a tree-building tool. We could also chat with people that has experience on building trees in the group, especially for TB (Kerri I guess?). I really think we should address this either by:
1) Externally, where `tbpore cluster` creates a file that can be parsed by a tree-building tool, and they can get the tree;
2) Internally, where `tbpore cluster` generates the tree itself.

Or we should give them a plausible and convincing justification why we shouldn't do it or why they don't need to do it (which I can't think of). We should remember that while we should not implement things that are out of scope of `tbpore`, they are also our main users, and this seems to be within the scope...

**Comment by FlorianePoint** [comment]
Hello, would it be possible to get the number of SNP in the clustering output (among the samples which belong to the same cluster) ?
Thanks
Floriane

**Comment by mbhall88** [comment]
Do you mean the number of SNPs between samples? Or from a sample to the reference?

**Comment by FlorianePoint** [comment]
actually both would be great

**Comment by mbhall88** [comment]
Inside the (`tbpore cluster`) output directory, there should be a directory name `.tbpore`. Inside that, there is the distance matrix `psdm.matrix.csv`. This will show you the number of SNPs between samples.

The number of SNPs between the reference and the same can be obtained from the `tbpore process` VCF file. You can use `bcftools` to count the number of SNPs that pass filtering with the following command

```
bcftools view -H -f '.,PASS' -i 'GT="alt"' vcf_file | wc -l
```

And obviously replace `vcf_file` with the path to the VCF file you want to count SNPs for.

If you want to create a VCF with only the passing variants, you can use that command above like so

```
bcftools view -H -f '.,PASS' -i 'GT="alt"' -o filtered.vcf vcf_file
```
where you can name `filtered.vcf` something more descriptive.

Hope this all makes sense?

**Comment by FlorianePoint** [comment]
Thanks for the instructions.
Regarding tbpore cluster, actually I only get a "cluster.txt" doc and a "logs" directory in my output directory, there is no directory named .tbpore
Otherwise I gave a trial for the SNPs and it worked well, thanks a lot!

**Comment by mbhall88** [comment]
> Regarding tbpore cluster, actually I only get a "cluster.txt" doc and a "logs" directory in my output directory, there is no directory named .tbpore

I should definitely be there (unless you used the `--cleanup` option?) It is a "hidden" directory - not sure what operating system you are using, but if you're using a file explorer you might need to look up how to show hidden files (e.g. cmd+shift+. on a mac). Or, if you're in the directory on the command line, you can list all files, including hidden ones, with `ls -la`

**Comment by FlorianePoint** [comment]
Hi Michael, correct, the directory .tbpore is there, hidden. 
Thanks

**Comment by jloubser** [comment]
@mbhall88 I'm being a nuisance, I'm sorry. We've been working on some alignment scripts using the consensus.fa output files. From a different pipeline (bovisanalyzer), we had to do the same where there it outputs a pseudogenome.fas file. I've noted that indels are ignored during variant calling, which of course makes sense for a basic snp-distance matrix and comparison. If indels were to be called and included and presented in the consensus.fa files as "-" characters, it could be used to build a tree by aligning the consensus.fa files, using snp-sites and then running iqtree. This is just a nore/suggestion perhaps for somewhere in the future :-) ''True" genetic distance are currently not presented in the consensus.fa files. I assume it's because it's more tricky to call an indel from ONT data and that false positives are more likely.

**Comment by mbhall88** [comment]
Hi @jloubser

Yeah, so tbpore was originally built to be a minimal implementation of the pipeline we used in the paper and for some of our collaborators. I have a project I am currently working on that will investigate indels for nanopore variant calling, but when this pipeline was written indel calling was pretty bad.  
For MTB, we find that people generally just call SNPs and do the SNP distance to define clusters so that's what we do here. I don't forsee us adding indels to the consensus anytime soon. But thank you for you input and suggestions.
